workspace(name = "org_brotli_research")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

local_repository(
    name = "org_brotli",
    path = "..",
)

new_git_repository(
    name = "divsufsort",
    build_file = "@//:BUILD.libdivsufsort",
    commit = "5f60d6f026c30fb4ac296f696b3c8b0eb71bd428",
    remote = "https://github.com/y-256/libdivsufsort",
)

new_git_repository(
    name = "esaxx",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
cc_library(
    name = "sais",
    hdrs = ["sais.hxx"],
    includes = ["."],
    include_prefix = "third_party/esaxx",
)
""",
    commit = "ca7cb332011ec37a8436487f210f396b84bd8273",
    remote = "https://github.com/hillbig/esaxx",
)
