package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

filegroup(
    name = "jni_src",
    srcs = [
        "decoder_jni.cc",
        "decoder_jni.h",
        # TODO: investigate, why this prevents JNI library loading.
        #"decoder_jni_onload.cc",
    ],
)

java_library(
    name = "dec",
    srcs = glob(
        ["*.java"],
        exclude = ["*Test*.java"],
    ),
    resource_jars = ["//:license"],
)

java_library(
    name = "test_lib",
    testonly = 1,
    srcs = glob(["*Test*.java"]),
    deps = [
        ":dec",
        "//org/brotli/integration:brotli_jni_test_base",
        "//org/brotli/integration:bundle_helper",
        "//org/brotli/wrapper/enc",
        "@maven//:junit_junit",
    ],
)

filegroup(
    name = "brotli_jni",
    srcs = ["//:brotli_jni.dll"],
)

filegroup(
    name = "test_bundle",
    srcs = ["//org/brotli/integration:test_data"],
)

java_test(
    name = "BrotliDecoderChannelTest",
    size = "large",
    data = [
        ":brotli_jni",  # Bazel JNI workaround
        ":test_bundle",
    ],
    jvm_flags = [
        "-DBROTLI_JNI_LIBRARY=$(location :brotli_jni)",
        "-DTEST_BUNDLE=$(location :test_bundle)",
    ],
    test_class = "org.brotli.wrapper.dec.BrotliDecoderChannelTest",
    runtime_deps = [":test_lib"],
)

java_test(
    name = "BrotliInputStreamTest",
    size = "large",
    data = [
        ":brotli_jni",  # Bazel JNI workaround
        ":test_bundle",
    ],
    jvm_flags = [
        "-DBROTLI_JNI_LIBRARY=$(location :brotli_jni)",
        "-DTEST_BUNDLE=$(location :test_bundle)",
    ],
    test_class = "org.brotli.wrapper.dec.BrotliInputStreamTest",
    runtime_deps = [":test_lib"],
)

java_test(
    name = "DecoderTest",
    size = "large",
    data = [
        ":brotli_jni",  # Bazel JNI workaround
        ":test_bundle",
    ],
    jvm_flags = [
        "-DBROTLI_JNI_LIBRARY=$(location :brotli_jni)",
        "-DTEST_BUNDLE=$(location :test_bundle)",
    ],
    test_class = "org.brotli.wrapper.dec.DecoderTest",
    runtime_deps = [":test_lib"],
)

java_test(
    name = "CornerCasesTest",
    size = "large",
    data = [
        ":brotli_jni",  # Bazel JNI workaround
    ],
    jvm_flags = [
        "-DBROTLI_JNI_LIBRARY=$(location :brotli_jni)",
    ],
    test_class = "org.brotli.wrapper.dec.CornerCasesTest",
    runtime_deps = [":test_lib"],
)
