# CMake generated Testfile for 
# Source directory: /home/lex_is1/Documents/Google/brotli-master
# Build directory: /home/lex_is1/Documents/Google/brotli-master/build_patch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(roundtrip/c/enc/encode.c/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=1" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/enc/encode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/encode.c.1" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=6" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/enc/encode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/encode.c.6" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=9" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/enc/encode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/encode.c.9" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=11" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/enc/encode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/encode.c.11" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=1" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/common/dictionary.h" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/dictionary.h.1" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=6" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/common/dictionary.h" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/dictionary.h.6" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=9" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/common/dictionary.h" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/dictionary.h.9" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=11" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/common/dictionary.h" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/dictionary.h.11" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=1" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/dec/decode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/decode.c.1" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=6" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/dec/decode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/decode.c.6" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=9" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/dec/decode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/decode.c.9" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DQUALITY=11" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/c/dec/decode.c" "-DOUTPUT=/home/lex_is1/Documents/Google/brotli-master/build_patch/decode.c.11" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;280;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(compatibility/tests/testdata/empty.compressed "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/tests/testdata/empty.compressed" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-compatibility-test.cmake")
set_tests_properties(compatibility/tests/testdata/empty.compressed PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;303;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
add_test(compatibility/tests/testdata/ukkonooa.compressed "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/lex_is1/Documents/Google/brotli-master/build_patch/brotli" "-DINPUT=/home/lex_is1/Documents/Google/brotli-master/tests/testdata/ukkonooa.compressed" "-P" "/home/lex_is1/Documents/Google/brotli-master/tests/run-compatibility-test.cmake")
set_tests_properties(compatibility/tests/testdata/ukkonooa.compressed PROPERTIES  _BACKTRACE_TRIPLES "/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;303;add_test;/home/lex_is1/Documents/Google/brotli-master/CMakeLists.txt;0;")
