from typing import Final

__version__: Final[str]
version: Final[str]

MODE_GENERIC: Final[int]
MODE_TEXT: Final[int]
MODE_FONT: Final[int]

class Compressor:
    def __init__(self, mode: int=..., quality: int=11, lgwin:int=22, lgblock:int=0): ...
    def process(self, string: bytes) -> bytes: ...
    def finish(self) -> bytes: ...
    def flush(self) -> bytes: ...


class Decompressor:
    def __init__(self): ...
    def is_finished(self) -> bool: ...
    def process(self, string: bytes) -> bytes: ...

def compress(string: bytes, mode: int=..., quality: int=11, lgwin:int=22, lgblock:int=0) -> bytes: ...

def decompress(string: bytes) -> bytes: ...

class error(Exception): ...
