# Description:
#   Java port of Brotli decoder.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

java_library(
    name = "prepared_dictionary",
    srcs = [
        "PreparedDictionary.java",
        "PreparedDictionaryGenerator.java",
    ],
)
