name: Scheduled Merge Remote Action
on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Merge Upstream
      uses: ethan42/merge-upstream@v4
      with:
        upstream: https://github.com/google/brotli
        upstream-branch: master
        branch: master
  mayhem-analysis:
    uses: ./.github/workflows/mayhem.yml
